//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_TiendaVirtual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public string Id_Usuario { get; set; }
        public string Productos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TotalProductos { get; set; }
        public Nullable<double> TotalPrecio { get; set; }
        public string NombreProductos { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
